# Generated by Django 4.2.30 on 2026-07-26 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0052_ligi_payment_override_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardlonglist',
            name='ligi_complete_at',
            field=models.DateTimeField(blank=True, help_text='When the WSCC marked Ligi Mashinani as complete', null=True),
        ),
        migrations.AddField(
            model_name='wardlonglist',
            name='ligi_complete_by',
            field=models.ForeignKey(blank=True, help_text='WSCC who marked Ligi Mashinani as complete', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ligi_completions_marked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wardlonglist',
            name='ligi_mashinani_complete',
            field=models.BooleanField(default=False, help_text='Marked True by the WSCC once all ward fixtures are done and a winner has been determined. Required before a Ward TM can be selected.'),
        ),
    ]
