# Generated by Django 6.0.2 on 2026-07-27 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0053_ligi_mashinani_complete_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WardVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_type', models.CharField(choices=[('main', 'Main Venue'), ('alternative', 'Alternative Venue')], default='main', help_text='Main venue or alternative venue', max_length=15)),
                ('name', models.CharField(help_text='Name of the ground or facility', max_length=200)),
                ('location_description', models.TextField(blank=True, default='', help_text='Physical location, landmarks, directions')),
                ('ward', models.CharField(blank=True, default='', help_text='Ward where this venue is located', max_length=100)),
                ('sub_county', models.CharField(blank=True, default='', help_text='Sub-county where this venue is located', max_length=100)),
                ('surface', models.CharField(blank=True, default='Natural Grass', help_text='Playing surface type (e.g. Natural Grass, Concrete, Tarmac)', max_length=100)),
                ('capacity', models.PositiveIntegerField(default=0, help_text='Estimated spectator capacity')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ward_venues_added', to=settings.AUTH_USER_MODEL)),
                ('discipline', models.ForeignKey(help_text='Ward discipline this venue belongs to', limit_choices_to={'level': 'ward'}, on_delete=django.db.models.deletion.CASCADE, related_name='ward_venues', to='teams.countydiscipline')),
            ],
            options={
                'verbose_name': 'Ward Venue',
                'verbose_name_plural': 'Ward Venues',
                'ordering': ['discipline', 'venue_type', 'name'],
            },
        ),
    ]
