# Generated by Django 6.0.2 on 2026-07-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0056_backfill_countyplayer_registered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countyplayer',
            name='director_locked',
            field=models.BooleanField(default=False, help_text='Locked by Director - Sports - no further edits except by Director'),
        ),
    ]
