# Generated by Django 4.2.30 on 2026-07-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0057_alter_countyplayer_director_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligimashinaniregistration',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mpesa', 'M-Pesa'), ('cash', 'Cash'), ('bank_slip', 'Bank Slip')], default='', help_text='How the team paid (M-Pesa, Cash, Bank Slip)', max_length=20),
        ),
    ]
