# Generated by Django 4.2.30 on 2026-07-30 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0058_add_payment_method_to_ligi_registration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='countydiscipline',
            unique_together=set(),
        ),
    ]
