# Generated by Django 4.2.30 on 2026-07-31 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0059_remove_countydiscipline_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligimashinaniregistration',
            name='county_discipline',
            field=models.OneToOneField(blank=True, help_text='The ward-level CountyDiscipline record created when this registration was approved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ligi_registration', to='teams.countydiscipline'),
        ),
    ]
