# Generated by Django 4.2.30 on 2026-07-31 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0060_add_county_discipline_fk_to_ligi_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardlonglist',
            name='discipline',
            field=models.ForeignKey(help_text='Ward discipline this longlist belongs to', limit_choices_to={'level': 'ward'}, on_delete=django.db.models.deletion.CASCADE, related_name='ward_longlists', to='teams.countydiscipline'),
        ),
    ]
