# Generated by Django 6.0.2 on 2026-08-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0061_wardlonglist_discipline_fk_not_o2o'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countyplayer',
            name='position',
            field=models.CharField(blank=True, default='', help_text='Player position (where applicable)', max_length=30),
        ),
    ]
