# Generated by Django 4.2.30 on 2026-08-06 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0062_position_max_length_30'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligitransferrequest',
            name='source_tm_notes',
            field=models.TextField(blank=True, default='', help_text='Source TM approval/rejection notes'),
        ),
        migrations.AddField(
            model_name='ligitransferrequest',
            name='source_tm_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ligitransferrequest',
            name='source_tm_reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Source team manager who approved/rejected release of this player', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_tm_transfer_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ligitransferrequest',
            name='status',
            field=models.CharField(choices=[('source_tm_pending', 'Awaiting Source Team Approval'), ('source_tm_rejected', 'Rejected by Source Team Manager'), ('pending', 'Pending WSCC Review'), ('wscc_approved', 'WSCC Approved  -  Pending SCSO'), ('wscc_rejected', 'Rejected by WSCC'), ('scso_approved', 'Approved  -  Transfer Complete'), ('scso_rejected', 'Rejected by Sub-County Officer'), ('senior_approved', 'Approved by Senior Official'), ('senior_rejected', 'Rejected by Senior Official'), ('withdrawn', 'Withdrawn by Team Manager')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ligitransferrequest',
            name='transfer_type',
            field=models.CharField(choices=[('within_ward', 'Within Same Ward (Team to Team)'), ('inter_ward', 'Inter-Ward (Same Sub-County)'), ('inter_subcounty', 'Inter-Sub-County')], default='inter_ward', help_text='Auto-computed: within_ward / inter_ward / inter_subcounty', max_length=20),
        ),
    ]
