/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(portal)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(portal)'}/longlist` | `/longlist`; params?: Router.UnknownInputParams; } | { pathname: `${'/(public)'}/fixtures` | `/fixtures`; params?: Router.UnknownInputParams; } | { pathname: `${'/(public)'}/results` | `/results`; params?: Router.UnknownInputParams; } | { pathname: `${'/(public)'}/standings` | `/standings`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(portal)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(portal)'}/longlist` | `/longlist`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(public)'}/fixtures` | `/fixtures`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(public)'}/results` | `/results`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(public)'}/standings` | `/standings`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(portal)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(portal)'}/longlist${`?${string}` | `#${string}` | ''}` | `/longlist${`?${string}` | `#${string}` | ''}` | `${'/(public)'}/fixtures${`?${string}` | `#${string}` | ''}` | `/fixtures${`?${string}` | `#${string}` | ''}` | `${'/(public)'}/results${`?${string}` | `#${string}` | ''}` | `/results${`?${string}` | `#${string}` | ''}` | `${'/(public)'}/standings${`?${string}` | `#${string}` | ''}` | `/standings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(portal)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(portal)'}/longlist` | `/longlist`; params?: Router.UnknownInputParams; } | { pathname: `${'/(public)'}/fixtures` | `/fixtures`; params?: Router.UnknownInputParams; } | { pathname: `${'/(public)'}/results` | `/results`; params?: Router.UnknownInputParams; } | { pathname: `${'/(public)'}/standings` | `/standings`; params?: Router.UnknownInputParams; };
    }
  }
}
