# Generated by Django 6.0.2 on 2026-07-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0009_update_levels_remove_experience_add_specialisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refereeprofile',
            name='level',
            field=models.CharField(default='County Grassroot', help_text='Officiating level (e.g. County Grassroot, National (KVF), FIBA International)', max_length=60),
        ),
        migrations.AlterField(
            model_name='refereeprofile',
            name='referee_type',
            field=models.CharField(default='referee', help_text="Official's role on match day (e.g. Referee, 1st Referee (R1), Umpire, Scorer)", max_length=40, verbose_name='Specialisation'),
        ),
    ]
