# Generated by Django 6.0.2 on 2026-07-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_role_max_length_40_add_sdc_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='magic_token',
            field=models.UUIDField(blank=True, help_text='Single-use login token included in the welcome email', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='magic_token_expires',
            field=models.DateTimeField(blank=True, help_text='Expiry date-time for the magic login token', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('competition_manager', 'Organising Secretary'), ('coordinator', 'Coordinator'), ('verification_officer', 'Verification Officer'), ('referee', 'Referee'), ('team_manager', 'Team Manager'), ('cec_sports', 'County CEC Member Sports'), ('treasurer', 'Treasurer'), ('jury_chair', 'Chair of the Jury'), ('media_manager', 'Media Manager'), ('secretary_general', 'Secretary General'), ('scout', 'Scout'), ('subcounty_sports_officer', 'Sub County Sports Officer'), ('chief_sports_officer', 'Chief Sports Officer'), ('director_sports', 'Director of Sports'), ('chief_officer_sports', 'Chief Officer Sports'), ('governor', 'Governor'), ('waziri_sports', 'Waziri Sports'), ('ward_sports_council_chair', 'Ward Sports Council Chair'), ('subcounty_discipline_coordinator', 'Subcounty Discipline Coordinator'), ('admin', 'System Admin')], default='team_manager', max_length=40),
        ),
    ]
