# Generated by Django 6.0.2 on 2026-07-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_user_role'),
        ('accounts', '0022_user_current_session_key'),
    ]

    operations = [
    ]
