# Generated by Django 4.2.30 on 2026-07-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_merge_20260730_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('competition_manager', 'Organising Secretary'), ('coordinator', 'Coordinator'), ('verification_officer', 'Verification Officer'), ('referee', 'Referee'), ('team_manager', 'Team Manager'), ('cec_sports', 'County CEC Member Sports'), ('jury_chair', 'Chair of the Jury'), ('media_manager', 'Media Manager'), ('scout', 'Scout'), ('subcounty_sports_officer', 'Sub County Sports Officer'), ('chief_sports_officer', 'Chief Sports Officer'), ('director_sports', 'Director - Sports'), ('chief_officer_sports', 'Chief Officer Sports'), ('governor', 'Governor'), ('waziri_sports', 'Waziri Sports'), ('ward_sports_council_chair', 'Ward Sports Council Chair'), ('subcounty_discipline_coordinator', 'Subcounty Discipline Coordinator'), ('admin', 'System Admin')], default='team_manager', max_length=40),
        ),
    ]
