# Generated by Django 4.2.30 on 2026-07-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0015_ligi_mashinani_pipeline_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='level',
            field=models.CharField(choices=[('ward', 'Ward (Ligi Mashinani)'), ('subcounty', 'Sub County MKJ Finals'), ('county', 'County MKJ Supa Cup')], default='county', help_text='Competition level in the pipeline', max_length=20),
        ),
    ]
